version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nalgebra
    versions:
    - 0.25.0
    - 0.25.1
    - 0.25.3
    - 0.25.4
    - 0.26.1
  - dependency-name: image
    versions:
    - 0.23.13
  - dependency-name: nom_stl
    versions:
    - 0.2.1
