[package]
name = "racy"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.24.0"
nom_stl = "0.2"
rayon = "1.5.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
